name: check & preview dns changes

on: pull_request

jobs:
  validate_job:
    runs-on: ubuntu-latest
    steps: 
      - shell: bash
      - uses: actions/checkout@v3
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}      
        run: |
          docker run -e CLOUDFLARE_API_TOKEN="${CLOUDFLARE_API_TOKEN}" --rm -it -v $(pwd)/dnsconfig.js:/dns/dnsconfig.js -v $(pwd)/creds.json:/dns/creds.json stackexchange/dnscontrol check
          docker run -e CLOUDFLARE_API_TOKEN="${CLOUDFLARE_API_TOKEN}" --rm -it -v $(pwd)/dnsconfig.js:/dns/dnsconfig.js -v $(pwd)/creds.json:/dns/creds.json stackexchange/dnscontrol preview